[[cells]]
name = "credential-revocation"
enable_type_id = false

  [cells.location]
  file = "digital-credentials-workspace/build/release/credential-revocation"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x8e42b1999f265a0078503c4acec4d5e134534297"
hash_type = "type"
